## Basic Configuration

#baseurl = "https://mchowning.github.io/mattchowning.com/" 
#baseurl = "http://mattchowning.com"
baseurl = "http://mattchowning.com/"
builddrafts = false
canonifyurls = true
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Matt Chowning"
title = "Matt Chowning"

theme = "goa"

## Hugo Built-in Features
# disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "UA-57944772-5"
enableRobotsTXT = true

## Site Settings
[params]
author = "Matt Chowning"
intro = "Father Husband Developer"
description = "Android developer, functional programming enthusiast, tennis player, Tottenham Hotspurs fan"
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
# [params.meta]
# description = "Simple minimalist theme"
# keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "mchowning"
# instagram = "<username>"
# xing = "<username>"
# linkedin = "<username>"
twitter = "mattchowning"
# facebook = "<username>"
# google = "<username>"
# stackoverflow = "<username>"
# email = "you@example.com"

## Extras
[params.extra]
copyright = "© 2018. Matt Chownning. [Some Rights Reserved](http://creativecommons.org/licenses/by/4.0/)." 
poweredby = true
highlightjs = true

## Main Menu
# [[menu.main]]
#     name = "blog"
#     weight = 100
#     identifier = "blog"
#     url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 100
    url = "/about/"
# [[menu.main]]
#     name = "coderag"
#     identifier = "coderag"
#     weight = 300
#     url = "/coderag/"
